### ISSUE TITLE
Can we update to use latest pymetis 

### ISSUE THREAD

**Issue by samcom12** [anuga-community/anuga_core#13]

**Comment by stoiver** [comment]
@samcom12, just wondering if you were asking about updating from version 4 to 5?

**Comment by samcom12** [comment]
@stoiver Yes. 
I was getting issues with finer mesh size and found a similar issue at 

http://glaros.dtc.umn.edu/gkhome/node/933

**Comment by stoiver** [comment]
@samcom12, `anuga` can already use metis 5, via the wrapper  https://github.com/inducer/pymetis. All you need to do is install `pymetis` via `pip` and then `anuga` will use the new version of metis.

**Comment by samcom12** [comment]
Yes, @stoiver, I did that, and that's why closed this issue earlier.
