### ISSUE TITLE
pybind11 not installed error

### ISSUE THREAD

**Issue by PetarMilevski** [anuga-community/anuga_core#24]
Hi Steve, how are you going?

I cloned the latest anuga on my ubuntu 20.04lts box and did sudo bash anuga_core/tools/install_ubuntu_20_04.sh to install and this error occurred. Tried this   python -m pip install pybind11, it says its installed but i keep getting the error. 

Any ideas??
```
  Building wheel for meshpy (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/petar/anuga_env/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-wm9zkzsj/meshpy/setup.py'"'"'; __file__='"'"'/tmp/pip-install-wm9zkzsj/meshpy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-gqp4dbqn
       cwd: /tmp/pip-install-wm9zkzsj/meshpy/
  Complete output (20 lines):
  ---------------------------------------------------------------------------
  Pybind11 is not installed.
  ---------------------------------------------------------------------------
  Very likely, the build process after this message will fail.
  
  Simply press Ctrl+C and type
  python -m pip install pybind11
  to fix this. If you don't, the build will continue
  in a few seconds.
  
  [1] https://pybind11.readthedocs.io/en/stable/
  ---------------------------------------------------------------------------
  Continuing in 1 seconds...    
  WARNING: The wheel package is not available.
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help
  
  error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for meshpy
  Running setup.py clean for meshpy
^CERROR: Operation cancelled by user
petar@petar:~$ python -m pip install pybind11
Requirement already satisfied: pybind11 in ./.local/lib/python3.8/site-packages (2.10.0)
```

**Comment by stoiver** [comment]
Hi Peter, Still plodding along. Waiting on the transplant.

Seems like there is a problem with installing meshpy.

Try installing meshpy via

python -m pip install meshpy

and see if that works.

Probably the installation script needs some work.

Cheers Steve

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Petar Milevski ***@***.***>
Sent: Wednesday, August 24, 2022 8:19:44 AM
To: anuga-community/anuga_core ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [anuga-community/anuga_core] pybind11 not installed error (Issue #24)


Hi Steve, how are you going?

I cloned the latest anuga on my ubuntu 20.04lts box and did sudo bash anuga_core/tools/install_ubuntu_20_04.sh to install and this error occurred. Tried this python -m pip install pybind11, it says its installed but i keep getting the error.

Any ideas??

Building wheel for meshpy (setup.py) ... error
ERROR: Command errored out with exit status 1:
command: /home/petar/anuga_env/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-wm9zkzsj/meshpy/setup.py'"'"'; file='"'"'/tmp/pip-install-wm9zkzsj/meshpy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(file);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, file, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-gqp4dbqn
cwd: /tmp/pip-install-wm9zkzsj/meshpy/
Complete output (20 lines):
Pybind11 is not installed.

Very likely, the build process after this message will fail.

Simply press Ctrl+C and type
python -m pip install pybind11
to fix this. If you don't, the build will continue
in a few seconds.

[1] https://pybind11.readthedocs.io/en/stable/<https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fpybind11.readthedocs.io%2Fen%2Fstable%2F&data=05%7C01%7Cstephen.roberts%40anu.edu.au%7C7a24f2887ca149ff4f4508da8559c7b8%7Ce37d725cab5c46249ae5f0533e486437%7C0%7C0%7C637968917892263914%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=0s82FMADRGmUqZUpbflAtnNrQVRYNch82VVP9fIkvZs%3D&reserved=0>

Continuing in 1 seconds...
WARNING: The wheel package is not available.
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
or: setup.py --help [cmd1 cmd2 ...]
or: setup.py --help-commands
or: setup.py cmd --help

error: invalid command 'bdist_wheel'

ERROR: Failed building wheel for meshpy
Running setup.py clean for meshpy
^CERROR: Operation cancelled by user
***@***.***:~$ python -m pip install pybind11
Requirement already satisfied: pybind11 in ./.local/lib/python3.8/site-packages (2.10.0)

**Comment by stoiver** [comment]
Hi Petar,

Another possible problem, the install script installs everything into a python env called anuga_env.

So you have to activate that environment via a command

source anuga_env/bin/activate

from your home directory. Your linux prompt should show that you are using the anuga_env environment. For instance my prompt looks like

(anuga_env) ***@***.***:~/anuga_core$

Then you should be able to check if pybind11 is installed in this environment. And if not install pybind11 via

pip install pybind11

and then try to install meshpy via

pip install meshpy

Cheers
Steve


==============================
Emeritus Prof Stephen Roberts
Mathematical Sciences Institute
Hanna Neumann Building #145
The Australian National University
Canberra, ACT 2600 AUSTRALIA
T: +61 2 61254445 | E: ***@***.***

CRICOS Provider: 00120C

________________________________
From: Petar Milevski ***@***.***>
Sent: Wednesday, 24 August 2022 8:19 AM
To: anuga-community/anuga_core ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [anuga-community/anuga_core] pybind11 not installed error (Issue #24)


Hi Steve, how are you going?

I cloned the latest anuga on my ubuntu 20.04lts box and did sudo bash anuga_core/tools/install_ubuntu_20_04.sh to install and this error occurred. Tried this python -m pip install pybind11, it says its installed but i keep getting the error.

Any ideas??

Building wheel for meshpy (setup.py) ... error
ERROR: Command errored out with exit status 1:
command: /home/petar/anuga_env/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-wm9zkzsj/meshpy/setup.py'"'"'; file='"'"'/tmp/pip-install-wm9zkzsj/meshpy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(file);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, file, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-gqp4dbqn
cwd: /tmp/pip-install-wm9zkzsj/meshpy/
Complete output (20 lines):
Pybind11 is not installed.

Very likely, the build process after this message will fail.

Simply press Ctrl+C and type
python -m pip install pybind11
to fix this. If you don't, the build will continue
in a few seconds.

[1] https://pybind11.readthedocs.io/en/stable/<https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fpybind11.readthedocs.io%2Fen%2Fstable%2F&data=05%7C01%7Cstephen.roberts%40anu.edu.au%7C7a24f2887ca149ff4f4508da8559c7b8%7Ce37d725cab5c46249ae5f0533e486437%7C0%7C0%7C637968917892263914%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=0s82FMADRGmUqZUpbflAtnNrQVRYNch82VVP9fIkvZs%3D&reserved=0>

Continuing in 1 seconds...
WARNING: The wheel package is not available.
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
or: setup.py --help [cmd1 cmd2 ...]
or: setup.py --help-commands
or: setup.py cmd --help

error: invalid command 'bdist_wheel'

ERROR: Failed building wheel for meshpy
Running setup.py clean for meshpy
^CERROR: Operation cancelled by user
***@***.***:~$ python -m pip install pybind11
Requirement already satisfied: pybind11 in ./.local/lib/python3.8/site-packages (2.10.0)

**Comment by PetarMilevski** [comment]
Hi Steve, so did all that and still the same issue. its really odd because
i did not have this issue when i installed on th ePC at the beginning of
the year.

I'll just continue to use the previous install.

regard

**Comment by stoiver** [comment]
Hi Petar, 

Just updated the install_ubuntu_20_04.sh script. 

Could you try it again.

Thanks
Steve

**Comment by PetarMilevski** [comment]
Hi Steve I'm working from home until Monday. It's my work PC that has the
issue. Will try it then and gets back to you.

**Comment by stoiver** [comment]
Hi Petar,

I was able to install an ubuntu 22.04 via the wsl system on windows. So at least the installation worked for that system.

Cheers
Steve




==============================
Emeritus Prof Stephen Roberts
Mathematical Sciences Institute
Hanna Neumann Building #145
The Australian National University
Canberra, ACT 2600 AUSTRALIA
T: +61 2 61254445 | E: ***@***.***

CRICOS Provider: 00120C

________________________________

**Comment by stoiver** [comment]
@PetarMilevski  is the lots of printout during the install procedure or when you run your own script?

**Comment by PetarMilevski** [comment]
When I'm running a model

**Comment by stoiver** [comment]
Seems the installation is now working for 22.04
