### ISSUE TITLE
run_open_slot_wide_bridge.py not working

### ISSUE THREAD

**Issue by PetarMilevski** [anuga-community/anuga_core#44]
in anuga_core/examples/structures/run_open_slot_wide_bridge.py

on line 46:

domain = rectangular_cross_domain(int(length/dx), int(width/dy),
                                  len1=length, len2=width)

should be 

points, vertices, boundary = rectangular_cross(int(length/dx), int(width/dy),
                                                    len1=length, len2=width)
domain = Domain(points, vertices, boundary) 

for model to run

**Comment by stoiver** [comment]
Hi Petar,

Thanks for drawing attention to the bug. Just got around to fixing it.

Cheers
Steve


[cid:6790a3b3-e0b1-4094-adce-a253c5d48116]

==============================
Emeritus Prof Stephen Roberts (he/him)
Mathematical Sciences Institute
Hanna Neumann Building #145
The Australian National University
Canberra, ACT 2600 AUSTRALIA
T: +61 2 61254445 | E: ***@***.***

CRICOS Provider: 00120C

________________________________
From: Petar Milevski ***@***.***>
Sent: Thursday, 11 January 2024 8:45 AM
To: anuga-community/anuga_core ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [anuga-community/anuga_core] run_open_slot_wide_bridge.py not working (Issue #44)


in anuga_core/examples/structures/run_open_slot_wide_bridge.py

on line 46:

domain = rectangular_cross_domain(int(length/dx), int(width/dy),
len1=length, len2=width)

should be

points, vertices, boundary = rectangular_cross(int(length/dx), int(width/dy),
len1=length, len2=width)
domain = Domain(points, vertices, boundary)

for model to run

**Comment by PetarMilevski** [comment]
Hi Steve

no worries.

How's life?

**Comment by stoiver** [comment]
Hi Petar,

We are just in the process of moving back to Canberra. We were here in Canberra for X-mas and had our stuff moved back just after X-mas and have been emptying boxes for the last couple of week.

Back to Adelaide next week for a few weeks to setup the house there for airbnb or rental.

So quite busy.

We will be happy when all the moving stuff has settled down.

It is good to essentially be back in Canberra.

Cheers
Steve

[cid:e8f220a9-1253-4854-acca-c7f3bf65cf26]

==============================
Emeritus Prof Stephen Roberts (he/him)
Mathematical Sciences Institute
Hanna Neumann Building #145
The Australian National University
Canberra, ACT 2600 AUSTRALIA
T: +61 2 61254445 | E: ***@***.***

CRICOS Provider: 00120C

________________________________
