### ISSUE TITLE
error in run_set_stage.py

### ISSUE THREAD

**Issue by PetarMilevski** [anuga-community/anuga_core#46]
Hi Steve, in anuga_core/examples/operators/run_set_stage.py

line 13 - ImportError: cannot import name 'float' from 'numpy'

line 37 - domain.set_flow_algorithm(2.0) - Unknown flow_algorithm. Possible choices are: DE0, DE1, DE2, DE0_7, DE1_7.

**Comment by stoiver** [comment]
@PetarMilevski  thanks. Just updated the file in the develop branch.
