### ISSUE TITLE
AttributeError: 'GPU_interface' object has no attribute 'extrapolate_kernel1'

### ISSUE THREAD

**Issue by Parikshit75** [anuga-community/anuga_core#47]
Hi all,

We've recently initiated the development of Anuga on GPU using the hackthon_development branch. However, during testing, we encountered the following error in the GPU_interface class when attempting to call the extrapolate_kernel1 attribute:

`AttributeError: 'GPU_interface' object has no attribute 'extrapolate_kernel1'`
Steps to Reproduce:

Load nvhpc and cuda.

Install Miniconda.

Create a Conda environment and activate it.

Install necessary packages using Conda and Pip:

```
conda install -c conda-forge cython dill future gitpython matplotlib netcdf4 numpy pytest pytz scipy setuptools wheel pip GDAL -y
pip install --no-cache cupy-cuda114 pmw utm meshpy pymetis pytriangle tzdata nvtx
```
Testing Steps:

Download the benchmark from [here](https://github.com/stoiver/anuga_pytest_benchmarks.git).
Run the benchmark using the following command:

python run_anuga_rectangular.py -mm 4
Environment:

Operating System: Linux-3.10.0-1160.el7.x86_64-x86_64-with-glibc2.17
Python Version: 3.10.13
GPU Model: Tesla V100-SXM2-16GB

We appreciate any insights or suggestions for resolving this issue. If you need further information or details, please let us know.

**Comment by samcom12** [comment]
@Parikshit75 seems it's resolved after clean built and using `nvc `compiler. closing it.
