### ISSUE TITLE
anuga has a read grid coding error while running on linux

### ISSUE THREAD

**Issue by yilou1** [anuga-community/anuga_core#51]
Hello, I am a newbie to using anuga.
I'm running it fine in windows, but running it in Ubuntu gives me read grid file encoding error and can't open grid file on behalf of the grid file.
This is my problem：
OSError: File mesh_1716207772.msh could not be opened

**Comment by stoiver** [comment]
@yilou1 It seems that either the contents of `mesh_1716207772.msh` may be corrupted. Can you check if the file exits (and is in the correct directory. Could the file be open by another program?  How big is the msh file?

**Comment by yilou1** [comment]
@stoiver 
Hello, I have confirmed that the file exists and there is no program occupying this file in the correct path, the grid file 35M is the same size as Windows. I uploaded the case run log. I am now investigating whether some encoding format caused the write or read error.
[slurm-1171.zip](https://github.com/anuga-community/anuga_core/files/15443871/slurm-1171.zip)

**Comment by stoiver** [comment]
@yilou1 how did you create the msh file? Good idea about it possibly being an encoding problem.

**Comment by stoiver** [comment]
@yilou1 did you run your code in parallel? 

On looking at the `slurm-1171.out` file, it seems to contain evidence of multiple creations of the mesh file. If so, make sure you only create your mesh file using processor 0. Ie put it in an if statement
```
if anuga.myid == 0:
...
```
Check out the examples in `examples/parallel`  to see how to create a mesh on processor 0 and distribute to the other processors.

**Comment by yilou1** [comment]
@stoiver  Hello, this is my error, I allocated two cpus to run. Thank you very much for your help. Thank you.
