### ISSUE TITLE
Inlet operator bug

### ISSUE THREAD

**Issue by stoiver** [anuga-community/anuga_core#53]
Just as with the rate operator, we need to change the xmom and ymom if the discharge Q is negative, to avoid unrealistically large velocities developing.

**Comment by PetarMilevski** [comment]
Hi Steve, what happens if the tailwater level is higher than the upstream
water level? Q will be negative as water is travelling upstream through a
bridge or culvert even those the channel slope is in the opposite
direction, just like when the tide is high?

**Comment by stoiver** [comment]
@PetarMilevski No worries Petar, this is specifically for the `Inlet_operator` and not the culvert and pipe operators. When using an `Inlet_operator` to remove water, at present the momentum is not changed (unless `zero_velocity` is set to `True`). In this case I have realised that if the depth of water goes to zero, and the momentum statis, then velocity can go to infinity. This showed up in the infiltration code https://github.com/betterflowinbays/anuga_infiltration for the `Rate_operator` and in our coupling code https://github.com/stoiver/anuga_drainage (where I dealt with the problem by adding the `zero_velocity` flag.

**Comment by PetarMilevski** [comment]
Ok, no worries Steve. Thanks
